### PR TITLE
Fix release notifications

### PR DESCRIPTION
**Pull request by OmarShehata**
Fixes https://github.com/CesiumGS/cesium-concierge/issues/142 to make the slack bot send individuals on the team reminders when the release is happening.

* Changed structured of the `.slackbot.yml` to be an array instead of a dict, so that people can be listed more than once
* Removed the weekly stats message which we're not really using anymore
* Updated unit tests
* Updated node to fix Travis, but can't use node 12 because of this issue https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node ?

I've tested this locally with a mock YAML and confirmed the Slack bot will message me. Here is what the 3 messages look like (I've updated the links to be AGI -> CesiumGS):

image

To do

* [x] Update release YAML in CesiumJS repo https://github.com/CesiumGS/cesium/pull/9179
* [ ] Deploy

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata! 
* :heavy_check_mark: Signed CLA found. 
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium-concierge/blob/release-bot/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by mramato** [comment]
Looks like deployment is still using Node 10: https://github.com/CesiumGS/cesium-concierge/blob/master/Dockerfile

Should probably use Node 10 in travis to so they match. (And 11 is technically unmaintained while 10 is still supported)

**Comment by mramato** [comment]
I didn't run it, but code looks fine to me and I trust you.

**Comment by OmarShehata** [comment]
Ah, yes my next question was how to make sure the deployed version is using a version of Node that works. Thanks Matt! 

I am confident this works since I tested it locally with a real Slack token. I will merge now and deploy tomorrow morning.

**Pull request merged**
