### PR TITLE
Remove check for google groups links for closed issues

### PR DESCRIPTION
**Pull request by hpinkos**
Removes checks on closed issues for groups.google.com links so cesium-concierge doesn't comment asking us to comment on outdated forum links.

@OmarShehata If you think it's important to update this for the new community forum, please open an issue.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos! 
* :heavy_check_mark: Signed CLA found. 
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium-concierge/blob/remove-forum-check/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by mramato** [comment]
@OmarShehata what's the plan here?

**Comment by OmarShehata** [comment]
It's on my list, but I don't think we should remove this check right now. We have lots of long standing issues that have been reported on the forum and would still be worth updating the associated threads on the new forum, since people still stumble on those old posts all the time.

So keeping it as-is is more useful to me than removing, because it's not that hard to find the same thread in the new forum by searching. 

With that said, my next step here is to re-evaluate is our strategy here: is it _worth_ updating these old threads, if we instead just say "This issue is a bug, see GitHub: <link>" then anyone stumbling on the old threads can still find the answer even if we don't explicitly update it. Or is there some easy integration we can do where the Concierge bot on the forum can automatically comment when the issue is closed?

**Comment by OmarShehata** [comment]
I do want to say thank you @hpinkos for bringing this up so it gets our attention.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @hpinkos! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

:sparkles: :sparkles: :sparkles:__I'm the Cesium Concierge and I'm here to test things.__ :sparkles: :sparkles: :sparkles:

**Pull request merged**
